create table if not exists public.financial_records (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  customer_id text not null,
  month date not null,
  month_index integer not null,
  event text not null default 'normal',
  income numeric not null,
  essential_spending numeric not null,
  discretionary_spending numeric not null,
  balance numeric not null,
  emi numeric not null,
  debt numeric not null,
  credit_limit numeric not null,
  credit_utilization numeric not null,
  missed_payments integer not null default 0,
  savings_buffer numeric not null,
  income_change_pct numeric not null,
  expense_to_income_pct numeric not null,
  unique (owner_id, customer_id, month)
);

create table if not exists public.interventions (
  id bigint generated by default as identity primary key,
  customer_id text not null,
  created_by uuid not null references auth.users(id) on delete cascade,
  action text not null default 'support_review',
  recommendation text,
  risk_score numeric,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.financial_records enable row level security;
alter table public.interventions enable row level security;

create policy "Users can read their financial records"
  on public.financial_records for select to authenticated
  using (owner_id = (select auth.uid()));

create policy "Users can read their interventions"
  on public.interventions for select to authenticated
  using (created_by = (select auth.uid()));

create policy "Users can create their interventions"
  on public.interventions for insert to authenticated
  with check (created_by = (select auth.uid()));

create index if not exists financial_records_customer_month_idx
  on public.financial_records (owner_id, customer_id, month);