"use client";

import { useState } from "react";
import { AdminShell } from "@/app/admin/admin-chrome";

const activity = [["Risk assessment", "C00042", "Sentinel API", "Completed", "09:42"], ["SHAP explanation", "C00042", "Sentinel API", "Completed", "09:41"], ["Intervention review", "C00042", "A. Khan", "Approved", "09:18"], ["Consent request", "C00118", "M. Patel", "Pending", "08:47"], ["Outreach scheduled", "C00077", "J. Lewis", "Recorded", "Yesterday"]];

export default function AuditPage() {
  const [filter, setFilter] = useState("All activity");
  const filtered = filter === "All activity" ? activity : activity.filter(([type]) => type.toLowerCase().includes(filter.toLowerCase().replace(" events", "")));
  return <AdminShell><section className="mx-auto max-w-[1400px] px-6 py-8 sm:px-10"><p className="text-sm font-medium text-[#3f8068]">Audit</p><h2 className="mt-1 text-3xl font-semibold tracking-[-.035em]">A clear record of what happened.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#708388]">Review the events around assessments and support decisions. This activity feed is intentionally illustrative.</p><div className="mt-8 rounded-2xl border border-[#f0d9a9] bg-[#fff8e9] px-5 py-4 text-xs text-[#86631c]"><span className="font-semibold">Demo audit data.</span> Events below are realistic examples for the prototype environment.</div><section className="mt-6 rounded-2xl border border-[#dfe7e8] bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-[#e7eeee] px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold">Activity log</h3><p className="mt-1 text-xs text-[#829397]">Last 24 hours · synthetic entries</p></div><div className="flex gap-2"><label htmlFor="audit-filter" className="sr-only">Filter audit events</label><select id="audit-filter" value={filter} onChange={(event) => setFilter(event.target.value)} className="rounded-lg border border-[#dfe7e8] bg-white px-3 py-2 text-xs text-[#31565b] outline-none"><option>All activity</option><option>Risk events</option><option>SHAP events</option><option>Intervention events</option><option>Consent events</option><option>Outreach events</option></select></div></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-[#f7faf9] text-[10px] uppercase tracking-wide text-[#829397]"><tr><th className="px-6 py-3 font-medium">Event</th><th className="px-4 py-3 font-medium">Customer</th><th className="px-4 py-3 font-medium">Actor</th><th className="px-4 py-3 font-medium">Status</th><th className="px-6 py-3 font-medium">Time</th></tr></thead><tbody className="divide-y divide-[#edf1f1]">{filtered.length ? filtered.map(([type, customer, actor, status, time]) => <tr key={`${type}-${customer}`}><td className="px-6 py-4 font-medium">{type}</td><td className="px-4 py-4 text-[#708388]">{customer}</td><td className="px-4 py-4 text-[#708388]">{actor}</td><td className="px-4 py-4"><span className="rounded-full bg-[#e9f4ee] px-2 py-1 text-[10px] text-[#3f8068]">{status}</span></td><td className="px-6 py-4 text-[#829397]">{time}</td></tr>) : <tr><td colSpan={5} className="px-6 py-12 text-center text-xs text-[#829397]">No demo events match this filter.</td></tr>}</tbody></table></div></section></section></AdminShell>;
}